---
# Source: mongodb-enterprise-operator/templates/operator-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise-operator
  namespace: mongodb
---
# Source: mongodb-enterprise-operator/templates/operator-roles.yaml
kind:  Role 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enterprise-operator
  namespace: mongodb
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - mongodb.com
  resources:
  - mongodb
  - mongodb/finalizers
  - mongodbusers
  - opsmanagers
  - opsmanagers/finalizers
  - mongodb/status
  - mongodbusers/status
  - opsmanagers/status
  verbs:
  - "*"
# This ClusterRoleBinding is necessary in order to use validating
# webhooks—these will prevent you from applying a variety of invalid resource
# definitions. The validating webhooks are optional so this can be removed if
# necessary.
---
# Source: mongodb-enterprise-operator/templates/operator-roles.yaml
kind:  RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enterprise-operator
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  Role 
  name: enterprise-operator
subjects:
- kind: ServiceAccount
  name: enterprise-operator
  namespace: mongodb

# This ClusterRole is needed if the user wants to use the Kubernetes CA
# infrastructure to generate certificates.
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-appdb
  namespace: mongodb
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-database-pods
  namespace: mongodb
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-ops-manager
  namespace: mongodb
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: mongodb
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-enterprise-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-enterprise-appdb
    namespace: mongodb
---
# Source: mongodb-enterprise-operator/templates/operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-operator
  namespace: mongodb
spec:
  replicas: 1
  selector:
      matchLabels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: enterprise-operator
        app.kubernetes.io/instance: enterprise-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: enterprise-operator
        app.kubernetes.io/instance: enterprise-operator
    spec:
      serviceAccountName: enterprise-operator
      containers:
      - name: mongodb-enterprise-operator
        image: registry.connect.redhat.com/mongodb/enterprise-operator:1.8.0
        imagePullPolicy: Always
        args:
          - "-watch-resource=mongodb"
          - "-watch-resource=opsmanagers"
          - "-watch-resource=mongodbusers"
        command:
          - "/usr/local/bin/mongodb-enterprise-operator"
        env:
        - name: OPERATOR_ENV
          value: prod
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CURRENT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MANAGED_SECURITY_CONTEXT
          value: 'true'
        - name: IMAGE_PULL_POLICY
          value: Always
        # Database
        - name: MONGODB_ENTERPRISE_DATABASE_IMAGE
          value: registry.connect.redhat.com/mongodb/enterprise-database
        - name: INIT_DATABASE_IMAGE_REPOSITORY
          value: registry.connect.redhat.com/mongodb/mongodb-enterprise-init-database
        - name: INIT_DATABASE_VERSION
          value: 1.0.0
        - name: DATABASE_VERSION
          value: 2.0.0
        # Ops Manager
        - name: OPS_MANAGER_IMAGE_REPOSITORY
          value: registry.connect.redhat.com/mongodb/mongodb-enterprise-ops-manager
        - name: INIT_OPS_MANAGER_IMAGE_REPOSITORY
          value: registry.connect.redhat.com/mongodb/mongodb-enterprise-init-ops-manager
        - name: INIT_OPS_MANAGER_VERSION
          value: 1.0.2
        # AppDB
        - name: APPDB_IMAGE_REPOSITORY
          value: registry.connect.redhat.com/mongodb/mongodb-enterprise-appdb
        - name: INIT_APPDB_IMAGE_REPOSITORY
          value: registry.connect.redhat.com/mongodb/mongodb-enterprise-init-appdb
        - name: INIT_APPDB_VERSION
          value: 1.0.4
        - name: OPS_MANAGER_IMAGE_PULL_POLICY
          value: Always
